name: documentacion_codecov

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build GestorDocumentacion
    - name: Test
      run: dotnet test --collect:"XPlat Code coverage" GestorDocumentacion
    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@e156083f13aff6830c92fc5faa23505779fbf649
      uses: codecov/codecov-action@v1.2.1
      with:
        # Repository upload token - get it from codecov.io. Required only for private repositories
        #token: # optional
        # Directory to search for coverage reports.
        directory: GestorDocumentacion
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        flags: documentacion
       
